/**
 * AUTO-GENERATED by scripts/generate-frames.mjs — do not edit by hand.
 * Re-generate with: npm run frames:generate
 */
import type { CustomSlot } from "@/types/template";

export interface FramePresetRect { x: number; y: number; width: number; height: number }

export interface FramePreset {
  id: string;
  name: string;
  description: string;
  /** Transparent PNG (alpha channel) overlay, served from /public/frames */
  image: string;
  cols: number;
  rows: number;
  /** cols * rows — must equal slots.length */
  total: number;
  /** Canvas size in px */
  width: number;
  height: number;
  /** Corner radius (px) of every photo hole */
  holeRadius: number;
  /** width / height */
  aspectRatio: number;
  type: "strip" | "grid";
  bg_color: string;
  text_color: string;
  badge: string;
  /** Exact transparent photo holes in canvas px (row-major: left→right, top→bottom) */
  holes: FramePresetRect[];
  /** Same holes in % of the canvas, enlarged by a few px so photos tuck under the border (no seams) */
  slots: CustomSlot[];
}

export const FRAME_PRESETS: FramePreset[] = [
  {
    "id": "birthday",
    "name": "Birthday",
    "description": "Ulang tahun pastel yang ceria dengan balon, bunting, dan kue.",
    "image": "/frames/birthday.png",
    "cols": 2,
    "rows": 3,
    "total": 6,
    "width": 1200,
    "height": 1638,
    "aspectRatio": 0.73,
    "holeRadius": 22,
    "type": "grid",
    "bg_color": "#FFF3E2",
    "text_color": "#E85D8A",
    "badge": "Birthday",
    "holes": [
      {
        "x": 60,
        "y": 240,
        "width": 522,
        "height": 392
      },
      {
        "x": 618,
        "y": 240,
        "width": 522,
        "height": 392
      },
      {
        "x": 60,
        "y": 668,
        "width": 522,
        "height": 392
      },
      {
        "x": 618,
        "y": 668,
        "width": 522,
        "height": 392
      },
      {
        "x": 60,
        "y": 1096,
        "width": 522,
        "height": 392
      },
      {
        "x": 618,
        "y": 1096,
        "width": 522,
        "height": 392
      }
    ],
    "slots": [
      {
        "x": 4.5,
        "y": 14.29,
        "width": 44.5,
        "height": 24.66
      },
      {
        "x": 51,
        "y": 14.29,
        "width": 44.5,
        "height": 24.66
      },
      {
        "x": 4.5,
        "y": 40.42,
        "width": 44.5,
        "height": 24.66
      },
      {
        "x": 51,
        "y": 40.42,
        "width": 44.5,
        "height": 24.66
      },
      {
        "x": 4.5,
        "y": 66.54,
        "width": 44.5,
        "height": 24.66
      },
      {
        "x": 51,
        "y": 66.54,
        "width": 44.5,
        "height": 24.66
      }
    ]
  },
  {
    "id": "nailong",
    "name": "Nailong",
    "description": "Dino kuning menggemaskan (karakter orisinal bergaya Nailong).",
    "image": "/frames/nailong.png",
    "cols": 1,
    "rows": 4,
    "total": 4,
    "width": 900,
    "height": 2850,
    "aspectRatio": 0.32,
    "holeRadius": 20,
    "type": "strip",
    "bg_color": "#FFE9A0",
    "text_color": "#C2570C",
    "badge": "Cute",
    "holes": [
      {
        "x": 60,
        "y": 210,
        "width": 780,
        "height": 585
      },
      {
        "x": 60,
        "y": 825,
        "width": 780,
        "height": 585
      },
      {
        "x": 60,
        "y": 1440,
        "width": 780,
        "height": 585
      },
      {
        "x": 60,
        "y": 2055,
        "width": 780,
        "height": 585
      }
    ],
    "slots": [
      {
        "x": 6,
        "y": 7.16,
        "width": 88,
        "height": 20.95
      },
      {
        "x": 6,
        "y": 28.74,
        "width": 88,
        "height": 20.95
      },
      {
        "x": 6,
        "y": 50.32,
        "width": 88,
        "height": 20.95
      },
      {
        "x": 6,
        "y": 71.89,
        "width": 88,
        "height": 20.95
      }
    ]
  },
  {
    "id": "hello-kitty",
    "name": "Hello Kitty",
    "description": "Kawaii pink dengan kucing putih berpita (karakter orisinal bergaya kawaii).",
    "image": "/frames/hello-kitty.png",
    "cols": 1,
    "rows": 4,
    "total": 4,
    "width": 900,
    "height": 2850,
    "aspectRatio": 0.32,
    "holeRadius": 20,
    "type": "strip",
    "bg_color": "#FFE3EC",
    "text_color": "#D6366B",
    "badge": "Kawaii",
    "holes": [
      {
        "x": 60,
        "y": 210,
        "width": 780,
        "height": 585
      },
      {
        "x": 60,
        "y": 825,
        "width": 780,
        "height": 585
      },
      {
        "x": 60,
        "y": 1440,
        "width": 780,
        "height": 585
      },
      {
        "x": 60,
        "y": 2055,
        "width": 780,
        "height": 585
      }
    ],
    "slots": [
      {
        "x": 6,
        "y": 7.16,
        "width": 88,
        "height": 20.95
      },
      {
        "x": 6,
        "y": 28.74,
        "width": 88,
        "height": 20.95
      },
      {
        "x": 6,
        "y": 50.32,
        "width": 88,
        "height": 20.95
      },
      {
        "x": 6,
        "y": 71.89,
        "width": 88,
        "height": 20.95
      }
    ]
  },
  {
    "id": "mickey-mouse",
    "name": "Mickey Mouse",
    "description": "Kartun klasik merah-hitam-kuning dengan sarung tangan dan bintang (desain orisinal).",
    "image": "/frames/mickey-mouse.png",
    "cols": 1,
    "rows": 4,
    "total": 4,
    "width": 900,
    "height": 2850,
    "aspectRatio": 0.32,
    "holeRadius": 20,
    "type": "strip",
    "bg_color": "#E3262E",
    "text_color": "#FFD23F",
    "badge": "Classic",
    "holes": [
      {
        "x": 60,
        "y": 210,
        "width": 780,
        "height": 585
      },
      {
        "x": 60,
        "y": 825,
        "width": 780,
        "height": 585
      },
      {
        "x": 60,
        "y": 1440,
        "width": 780,
        "height": 585
      },
      {
        "x": 60,
        "y": 2055,
        "width": 780,
        "height": 585
      }
    ],
    "slots": [
      {
        "x": 6,
        "y": 7.16,
        "width": 88,
        "height": 20.95
      },
      {
        "x": 6,
        "y": 28.74,
        "width": 88,
        "height": 20.95
      },
      {
        "x": 6,
        "y": 50.32,
        "width": 88,
        "height": 20.95
      },
      {
        "x": 6,
        "y": 71.89,
        "width": 88,
        "height": 20.95
      }
    ]
  },
  {
    "id": "perunggu",
    "name": "Band Perunggu",
    "description": "Editorial alternatif Indonesia: kertas, grain film, garis tipis, earth tone.",
    "image": "/frames/perunggu.png",
    "cols": 1,
    "rows": 3,
    "total": 3,
    "width": 900,
    "height": 2235,
    "aspectRatio": 0.4,
    "holeRadius": 8,
    "type": "strip",
    "bg_color": "#D9CFBD",
    "text_color": "#2B2118",
    "badge": "Indie",
    "holes": [
      {
        "x": 60,
        "y": 190,
        "width": 780,
        "height": 585
      },
      {
        "x": 60,
        "y": 805,
        "width": 780,
        "height": 585
      },
      {
        "x": 60,
        "y": 1420,
        "width": 780,
        "height": 585
      }
    ],
    "slots": [
      {
        "x": 6,
        "y": 8.23,
        "width": 88,
        "height": 26.71
      },
      {
        "x": 6,
        "y": 35.75,
        "width": 88,
        "height": 26.71
      },
      {
        "x": 6,
        "y": 63.27,
        "width": 88,
        "height": 26.71
      }
    ]
  },
  {
    "id": "formula-1",
    "name": "Formula 1",
    "description": "Motorsport merah-hitam dengan bendera kotak-kotak dan garis kecepatan.",
    "image": "/frames/formula-1.png",
    "cols": 1,
    "rows": 3,
    "total": 3,
    "width": 900,
    "height": 2235,
    "aspectRatio": 0.4,
    "holeRadius": 6,
    "type": "strip",
    "bg_color": "#141414",
    "text_color": "#FFFFFF",
    "badge": "Racing",
    "holes": [
      {
        "x": 60,
        "y": 190,
        "width": 780,
        "height": 585
      },
      {
        "x": 60,
        "y": 805,
        "width": 780,
        "height": 585
      },
      {
        "x": 60,
        "y": 1420,
        "width": 780,
        "height": 585
      }
    ],
    "slots": [
      {
        "x": 6,
        "y": 8.23,
        "width": 88,
        "height": 26.71
      },
      {
        "x": 6,
        "y": 35.75,
        "width": 88,
        "height": 26.71
      },
      {
        "x": 6,
        "y": 63.27,
        "width": 88,
        "height": 26.71
      }
    ]
  },
  {
    "id": "vintage",
    "name": "Vintage",
    "description": "Retro film analog dalam tone beige & cokelat, 8 foto.",
    "image": "/frames/vintage.png",
    "cols": 2,
    "rows": 4,
    "total": 8,
    "width": 1200,
    "height": 1974,
    "aspectRatio": 0.61,
    "holeRadius": 6,
    "type": "grid",
    "bg_color": "#EFE3CC",
    "text_color": "#5A3E26",
    "badge": "Retro",
    "holes": [
      {
        "x": 70,
        "y": 170,
        "width": 515,
        "height": 386
      },
      {
        "x": 615,
        "y": 170,
        "width": 515,
        "height": 386
      },
      {
        "x": 70,
        "y": 586,
        "width": 515,
        "height": 386
      },
      {
        "x": 615,
        "y": 586,
        "width": 515,
        "height": 386
      },
      {
        "x": 70,
        "y": 1002,
        "width": 515,
        "height": 386
      },
      {
        "x": 615,
        "y": 1002,
        "width": 515,
        "height": 386
      },
      {
        "x": 70,
        "y": 1418,
        "width": 515,
        "height": 386
      },
      {
        "x": 615,
        "y": 1418,
        "width": 515,
        "height": 386
      }
    ],
    "slots": [
      {
        "x": 5.33,
        "y": 8.31,
        "width": 43.92,
        "height": 20.16
      },
      {
        "x": 50.75,
        "y": 8.31,
        "width": 43.92,
        "height": 20.16
      },
      {
        "x": 5.33,
        "y": 29.38,
        "width": 43.92,
        "height": 20.16
      },
      {
        "x": 50.75,
        "y": 29.38,
        "width": 43.92,
        "height": 20.16
      },
      {
        "x": 5.33,
        "y": 50.46,
        "width": 43.92,
        "height": 20.16
      },
      {
        "x": 50.75,
        "y": 50.46,
        "width": 43.92,
        "height": 20.16
      },
      {
        "x": 5.33,
        "y": 71.53,
        "width": 43.92,
        "height": 20.16
      },
      {
        "x": 50.75,
        "y": 71.53,
        "width": 43.92,
        "height": 20.16
      }
    ]
  },
  {
    "id": "flowers",
    "name": "Flowers",
    "description": "Floral lembut: krem, sage, pink pastel, dan lavender.",
    "image": "/frames/flowers.png",
    "cols": 1,
    "rows": 3,
    "total": 3,
    "width": 900,
    "height": 2195,
    "aspectRatio": 0.41,
    "holeRadius": 22,
    "type": "strip",
    "bg_color": "#FBF7EF",
    "text_color": "#5E7F5A",
    "badge": "Floral",
    "holes": [
      {
        "x": 60,
        "y": 190,
        "width": 780,
        "height": 585
      },
      {
        "x": 60,
        "y": 805,
        "width": 780,
        "height": 585
      },
      {
        "x": 60,
        "y": 1420,
        "width": 780,
        "height": 585
      }
    ],
    "slots": [
      {
        "x": 6,
        "y": 8.38,
        "width": 88,
        "height": 27.2
      },
      {
        "x": 6,
        "y": 36.4,
        "width": 88,
        "height": 27.2
      },
      {
        "x": 6,
        "y": 64.42,
        "width": 88,
        "height": 27.2
      }
    ]
  }
];
